apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cert
  template:
    metadata:
      labels:
        app: cert
    spec:
      containers:
        - name: center-ctn
          image: choicco89/aws9-eks-center:v1
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "200m"
              memory: "256Mi"
            limits:
              cpu: "500m"
              memory: "512Mi"

        - name: stress
          image: progrium/stress
          args: ["--cpu", "1", "--timeout", "300s"]
          resources:
            requests:
              cpu: "300m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"